{{- $fullName := include "sftp-server.fullname" . -}}
{{- range .Values.sftpConfig.users }}
{{- if gt (len .authorizedKeys) 0 -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $fullName }}-authorized-keys-{{ .userName }}
data:
    {{- range $keyName, $rsaKey := .authorizedKeys }}
      {{ $keyName }}: |
        {{ $rsaKey }}
    {{- end }}
{{- end -}}
{{- end }}