{{- $fullName := include "sftp-server.fullname" . -}}
{{- range .Values.sftpConfig.users }}
{{- if gt (len .authorizedKeys) 0 -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $fullName }}-authorized-keys-{{ .userName }}
data:
    {{- toYaml .authorizedKeys | nindent 4 }}
{{- end -}}
{{- end }}