{{- if .Values.ingressEnabled }}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: {{ template "sftp-server.fullname" . }}

spec:
  entryPoints:
    - sftp
  routes:
  - match: HostSNI(`*`)
    services:
    - name: {{ template "sftp-server.fullname" . }}
      port: 22
{{- end }}
