{{- if .Values.initScript.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "sftp-server.fullname" . }}-init-script-env
  labels:
    {{- include "sftp-server.labels" . | nindent 4 }}
    {{- if .Values.additionalLabels }}
{{ toYaml .Values.additionalLabels | indent 4 }}
    {{- end }}
data:
{{ toYaml .Values.initScript.env | indent 2 }}
{{- end }}
